### ISSUE TITLE
Show screenshots of GRASS GIS intead of banner?

### ISSUE THREAD

**Issue by SunveerSingh** [OSGeo/grass-website#124]
On the landing page, I think it would be more appropriate to show GRASS GIS screenshots instead of the GRASS Banner. For eg: screenshots which are being displayed here https://grass.osgeo.org/screenshots/ we can display them in the place of banner.

**Comment by neteler** [comment]
I suppose you are referring to the current (oldish) website?

We are working on a completely new website, see https://staging.grass.osgeo.org/

There is a gallery ticket open: #25

**Comment by cmbarton** [comment]
Yes. I was looking at the current site not the new one in development.

On the old site, all listed versions should perhaps say:

"These are all-inclusive GRASS binary apps. They include all needed dependencies, as well as required Python and wxPython versions. GRASS 7.8.2 and higher versions are compiled with Python 3; earlier versions are compiled with Python 2.7. "

Delete a reference to frameworks

The links for GRASS 7.6 and 7.8 are http://grassmac.wikidot.com
The link for GRASS 7.9 is http://grassmac.wikidot.com/downloads

Both are correct but we should probably be consistent.
http://grassmac.wikidot.com/downloads goes directly to my download page
http://grassmac.wikidot.com goes to the main site page with some information about GRASS in general and an overview of the binaries.

-----

For the new site, the Kingchaos site refers back to my site. So it should not be listed for binaries. The frameworks on that site are only useful for very old versions of my binaries, but may be useful for homebrew (I don't know).

With the recent bug fixes, I do now have binaries for GRASS 7.8.2 and 7.9. I use 7.8.2 RB instead of stable because it has important bug fixes needed for compiling and for the digitizer.

Vaclav may have an Anaconda recipe working (not sure where that is, but he was close a couple weeks back) that should probably also be listed if working.

Thanks
Michael


____________________
C. Michael Barton
Director, Center for Social Dynamics & Complexity
Professor of Anthropology, School of Human Evolution & Social Change
Head, Graduate Faculty in Complex Adaptive Systems Science
Arizona State University

voice:  480-965-6262 (SHESC), 480-965-8130/727-9746 (CSDC)
fax: 480-965-7671 (SHESC),  480-727-0709 (CSDC)
www: http://www.public.asu.edu/~cmbarton, https://complexity.asu.edu/csdc

















On Apr 26, 2020, at 9:17 AM, Markus Neteler <notifications@github.com<mailto:notifications@github.com>> wrote:



I suppose you are referring to the current (oldish) website?

We are working on a completely new website, see https://staging.grass.osgeo.org/

There is a gallery ticket open: #25<https://github.com/OSGeo/grass-website/issues/25>

**Comment by SunveerSingh** [comment]
@neteler I was referring to the new website. I meant that here https://staging.grass.osgeo.org/ on the landing page there is a banner with grass background, instead of it we can show actual GRASS GIS screenshots.

**Comment by neteler** [comment]
> Yes. I was looking at the current site not the new one in development. On the old site, all listed versions should perhaps say: "These are all-inclusive GRASS binary apps. 

... Michael, you are editing an unrelated ticket. I have separated out your comment into #126.

This issue is about "gallery".

**Comment by lucadelu** [comment]
> @neteler I was referring to the new website. I meant that here https://staging.grass.osgeo.org/ on the landing page there is a banner with grass background, instead of it we can show actual GRASS GIS screenshots.

I like the banner solution, however could you point us to an appropriate image?

**Comment by SunveerSingh** [comment]
@lucadelu here we can find some screenshots of user interface of GRASS GIS https://grass.osgeo.org/screenshots/user-interface/ or we can also create a new screenshots for the banner.

 Also, I am unable to find the appropriate source file of https://staging.grass.osgeo.org/ such that I would fork and do changes in my fork then show it as a example to the members.

**Comment by neteler** [comment]
> Also, I am unable to find the appropriate source file of https://staging.grass.osgeo.org/ 

The gallery files are here:
https://staging.grass.osgeo.org/images/gallery/

**Comment by SunveerSingh** [comment]
> The gallery files are here:
> https://staging.grass.osgeo.org/images/gallery/
Thanks, also what about code files such as .html, where we can do changes?

**Comment by neteler** [comment]
AFAIK you have to check out this PR to get the code as it isn't merged yet.

**Comment by lucadelu** [comment]
> @lucadelu here we can find some screenshots of user interface of GRASS GIS https://grass.osgeo.org/screenshots/user-interface/ or we can also create a new screenshots for the banner.
> 

Ok, but none of that screenshot fit well for my point of view

> Also, I am unable to find the appropriate source file of https://staging.grass.osgeo.org/ such that I would fork and do changes in my fork then show it as a example to the members.

The file/line to modify is https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/index.html#L8

**Comment by SunveerSingh** [comment]
> Ok, but none of that screenshot fit well for my point of view

What type of screenshots do you suggest? Should we create a collage or something with appropriate size?

**Comment by nbozon** [comment]
I am not in favor of removing the GRASS weed photograph banner, as the new theme is very much built on it.
Replacing it by a screenshots collage may strongly overload the home page design and harm the visitor experience.
The banner is also using a css gradient which is set to fit the background image at best, that should also be changed if you would change the banner. I think selected screenshots could be added bellow on the home page, but using them in the banner would really break the webdesign imo.

**Comment by veroandreo** [comment]
I'm also against removing the banner or replacing it with screenshots. A dynamic/sliding gallery could instead be added to the home page as was suggested in https://github.com/OSGeo/grass-website/pull/133#issuecomment-623153851.

**Comment by neteler** [comment]
Thanks to @nbozon there is now a slideshow on the landing page, cool!

Small issue: one http (instead of https) leaks in there, which creates an issue with the SSL certificate recognition:

![image](https://user-images.githubusercontent.com/1295172/88285288-1e8c9080-ccef-11ea-931f-ab850b825a41.png)

Seems to be gallery related since I only saw it on the updated landing page...

**Comment by neteler** [comment]
If @SunveerSingh  agrees, we might close this report as done.

**Comment by SunveerSingh** [comment]
@neteler Yes, it really look great. Should I close it?

**Comment by neteler** [comment]
Yes, please
