### ISSUE TITLE
font awesome icons do not display properly in subpages

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#20]
Font awesome icons display fine in the landing page, but they do not display properly in the pages under the different menus. See for example the temporal icon and footer in http://staging.grass.osgeo.org/learn/manuals/ or the footer in http://staging.grass.osgeo.org/learn/overview/

**Comment by nbozon** [comment]
Thx for the report @veroandreo , they should show up now,  but there are still some errors. 

Theses icons are generally shown on the website as svg (at least in my browser), they may not on some browsers. 
Fontawesome is stored locally in themes/grass/static/plugins/fontawesome, available in several formats for fallbacks in different browsers:
<img width="233" alt="Capture d’écran 2020-03-22 à 08 08 17" src="https://user-images.githubusercontent.com/7135374/77244383-8c775d00-6c14-11ea-86b9-4ce001d26ac8.png">

It seems ttf and woff / woff2 files throw the following error on the page where the icons are used:

    Access to font at 'https://staging.grass.osgeo.org/plugins/fontawesome/fonts/fontawesome-webfont.ttf?v=4.7.0' from origin 'http://staging.grass.osgeo.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is confirmed by (no Access-Control-Allow-Origin: *:  in the response)

    curl -I https://staging.grass.osgeo.org/plugins/fontawesome/fonts/fontawesome-webfont.ttf?v=4.7.0

@neteler I suggest to edit the nginx config as follow, in order to get rid of those errors

    if ($filename ~* ^.*?\.(eot)|(ttf)|(woff)|(woff2) $){
	add_header Access-Control-Allow-Origin *;
    }

**Comment by nbozon** [comment]
if ($filename ~* ^.*?\.(eot)|(ttf)|(woff)|(woff2) $){
     add_header Access-Control-Allow-Origin 'https://staging.grass.osgeo.org';
    }

would probably be safer

**Comment by neteler** [comment]
@nbozon indeed it is an Apache server, not nginx - do you have the "magic lines" also for that? Mercì

**Comment by nbozon** [comment]
<FilesMatch ".(eot|ttf|otf|woff|woff2)">
	    Header set Access-Control-Allow-Origin "*"
    </FilesMatch>

should then do the trick for the Apache config @neteler

**Comment by nbozon** [comment]
or 

    <FilesMatch ".(eot|ttf|otf|woff|woff2)">
        Header set Access-Control-Allow-Origin "https://staging.grass.osgeo.org"
    </FilesMatch>

**Comment by neteler** [comment]
ok, I have now reconfigured the server:

```
a2enmod headers
systemctl restart apache2

# added above to
vim /etc/apache2/sites-enabled/000-default.conf
```

**Comment by neteler** [comment]
> Font awesome icons display fine in the landing page, but they do not display properly in the pages under the different menus. See for example the temporal icon and footer in http://staging.grass.osgeo.org/learn/manuals/ or the footer in http://staging.grass.osgeo.org/learn/overview/

Please check again, after the fix of #26 it now seems to be ok.

**Comment by nbozon** [comment]
+1 , fontawesome 4.7 icons are now displayed correctly and can be used from anywhere in the theme

**Comment by neteler** [comment]
Great, one problem done!
