### ISSUE TITLE
Landing page with mixed content breaking SSL

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#203]
Issue with the SSL certificate on landing page (elsewhere it is fine):

![image](https://user-images.githubusercontent.com/1295172/88593926-9563b980-d060-11ea-84df-99ade96a2226.png)

I don't know the reason. But let's fix it for the official announcement of https://grass.osgeo.org/ on **29 Jul 2020**, please.

_Originally posted by @neteler in https://github.com/OSGeo/grass-website/issues/124#issuecomment-662973532_

**Comment by lucadelu** [comment]
Using [this](https://www.jitbit.com/sslcheck/) seems that pages with problem are:
- https://grass.osgeo.org/news/2013_07_30_stable_grass_gis_6_4_3_released/ 
- https://grass.osgeo.org/grass74/manuals/libpython/index.html

they have links to http:// pages, probably changing this could fix the problem, what do you think?

**Comment by neteler** [comment]
Regina thinks it comes from https://fakeimg.pl/200x85/f9f9f9/088b36/?text=coming%20soon&font=noto being included in the landing page

**Comment by nbozon** [comment]
Regina is right ! Now fixed in master 
The fakeimg link was replaced by the generated PNG image, now lying in /images/other/
(https://github.com/OSGeo/grass-website/commit/dea923a2c5c4463b5c7d8cb2b91bac517a434ec3#diff-6afc5a35d14b4462ccc8d5ea1cd181b7 )
Home page appears as secured again here, sorry for the inconvenience

**Comment by nbozon** [comment]
@neteler @lucadelu can you please check and close this ticket ? thx

**Comment by neteler** [comment]
Yes, it looks good now, thanks. Closing
