### ISSUE TITLE
Update Global Datasets

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass-website#454]
@ecodiv @veroandreo Update the global datasets on the [Data](https://grass.osgeo.org/download/data/) page to their latest releases (v2.0.0). 

* [Basic global dataset](https://zenodo.org/doi/10.5281/zenodo.3762773) [DOWNLOAD ZIP (121.3 MB)](https://zenodo.org/records/3762852/files/natural-earth-dataset.zip?download=1)
* [Full global dataset](https://doi.org/10.5281/zenodo.13370326) [DOWNLOAD ZIP (2.2 GB)](https://zenodo.org/records/13370326/files/global-dataset.zip?download=1)

**Comment by ecodiv** [comment]
@veroandreo @neteler will this also update the download of the sample data from within GRASS? Or does this require a separate request  in the grass gis repository?

> @ecodiv @veroandreo Update the global datasets on the [Data](https://grass.osgeo.org/download/data/) page to their latest releases (v2.0.0).
> 
>     * [Basic global dataset](https://zenodo.org/doi/10.5281/zenodo.3762773) [DOWNLOAD ZIP (121.3 MB)](https://zenodo.org/records/3762852/files/natural-earth-dataset.zip?download=1)
> 
>     * [Full global dataset](https://doi.org/10.5281/zenodo.13370326) [DOWNLOAD ZIP (2.2 GB)](https://zenodo.org/records/13370326/files/global-dataset.zip?download=1)

The basic dataset URL should be https://zenodo.org/records/13370131/files/natural_earth_dataset.zip, I think?

**Comment by neteler** [comment]
> * [Basic global dataset](https://zenodo.org/doi/10.5281/zenodo.3762773)

May I suggest to better use: https://doi.org/10.5281/zenodo.3762773 ?

**Comment by neteler** [comment]
> will this also update the download of the sample data from within GRASS? Or does this require a separate request in the grass gis repository?

As it is a separate repository, a source code related pull request is needed there.
Seems you already opened it at https://github.com/OSGeo/grass/pull/4223

**Comment by baharmon** [comment]
With correct links:

[Basic global dataset](https://doi.org/10.5281/zenodo.3762773) [DOWNLOAD ZIP (121.3 MB)](https://zenodo.org/records/13370131/files/natural_earth_dataset.zip?download=1)

[Full global dataset](https://doi.org/10.5281/zenodo.13370326) [DOWNLOAD ZIP (2.2 GB)](https://zenodo.org/records/13370326/files/global-dataset.zip?download=1)

**Comment by wenzeslaus** [comment]
To the topic of authors (GRASS Development Team was suggested in #4172), while I think we should make an effort to acknowledge everyone, I'm not convinced "GRASS Development Team" is helping that. It is trying to acknowledge everyone and it may end up acknowledging no one because there are no names. Another issue is providing the citation for that. While I have seen some efforts to deal with a group being an author, citations systems mostly count on individual people being authors. Having a "group author" then complicates lives of people who want to cite the dataset. And, when a "group author" does not translate well into individual names, it also does not count as a citation for anyone. I would prefer if, e.g., people involved in the issue and PR are included as authors since they were the ones forming it or even just the two people who actually dealt with the data.
