### ISSUE TITLE
Useful links are displayed before content on mobile devices

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-website#79]
On (at least smaller) mobile devices, "Useful links" are displayed before content, which is a bit confusing. Would it be possible to display such (I guess) less essential information at the bottom?
See e.g.:
https://staging.grass.osgeo.org/contribute/development/
on your mobile phone...

**Comment by mlennert** [comment]
AFAIK, this is not only on mobile devices. I agree that these links are confusing where they are. I'd rather see some form of table of contents of the page, especially for this one which is quite long.

**Comment by lucadelu** [comment]
I resolved using classes flex-row and flex-row-inverse 23d39a8
@nbozon is this solution working well?

@ninsbl @mlennert are there other pages with this problem?

**Comment by mlennert** [comment]
> I resolved using classes flex-row and flex-row-inverse [23d39a8](https://github.com/OSGeo/grass-website/commit/23d39a80ad433cc2eb6011faf732050c0f6d72a4)
> @nbozon is this solution working well?
> 
> @ninsbl @mlennert are there other pages with this problem?

No, I think this is the only page where these is something like "Useful links". My more fundamental question would be: should this list of links be where it is ? My first reflex when I see it is to think this is a table of contents of the page and links to sections of it.

Personally, I would expect such a useful links page at the end, or, in this case, maybe not even at all since the first link corresponds to the first entry in the page, so why create to paths to the bug tracker ?

I think as we are creating fairly long pages (which I think could be considered as a problem in itself), we might want to add some form of ToC at the top of each page. Or rather use this /develoment page as a landing page and break down each form of contribution to a new page. That way, you would have quick access to each subject.

**Comment by mlennert** [comment]
See also discussions in #120.

**Comment by nbozon** [comment]
Inverting the column order in the devel.html layout file somehow solves this issue.
The Quick links are now always displayed after the main content on mobile, see
<img width="211" alt="Capture d’écran 2020-05-24 à 10 48 52" src="https://user-images.githubusercontent.com/7135374/82749845-4e312200-9dac-11ea-9737-740dead5bcab.png">
Please close this issue or at least remove the blocker tag @ninsbl @mlennert @lucadelu . We may also remove the quick links completely if needed.

**Comment by lucadelu** [comment]
fine for me, however did you try my solution of flex-column-reverse https://github.com/lucadelu/grass-website/commit/23d39a80ad433cc2eb6011faf732050c0f6d72a4 ?

**Comment by nbozon** [comment]
@lucadelu yes i also tried it thanks,working nicely, and can probably be used for other cases too.
